export const TOGGLE_SHOW_INACTIVE: string = 'CONTACTS_LIST/TOGGLE_SHOW_INACTIVE';
export const TOGGLE_SHOW_CHILDREN: string = 'CONTACTS_LIST/TOGGLE_SHOW_CHILDREN';
export const SET_BASIC_LIST: string = 'CONTACTS_LIST/SET_BASIC_LIST';
export const REFRESH_PROCESS_LIST: string = 'CONTACTS_LIST/REFRESH_PROCESS_LIST';
